-- LinkedIn & Website Enrichment SQL
-- 226 companies enriched

BEGIN;
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/rabeh-platform/', linkedin_company_url = 'https://www.linkedin.com/company/rabeh-platform/' WHERE id = '00451d23-f5bd-452e-8a23-44f383a3b754'; -- rab
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/lendo/', linkedin_company_url = 'https://www.linkedin.com/company/lendo/' WHERE id = '00d30a15-3859-4314-a60b-4d2a499bc893'; -- Lendo
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/w3i/', linkedin_company_url = 'https://www.linkedin.com/company/w3i/', website_url = 'https://w3i.io' WHERE id = '01807ba3-07d7-4203-9023-f8c54ba4aa34'; -- w3i
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/conduit-finance/', linkedin_company_url = 'https://www.linkedin.com/company/conduit-finance/' WHERE id = '02259715-82ca-433c-8c26-c938565ed26c'; -- Conduit
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/plus500/', linkedin_company_url = 'https://www.linkedin.com/company/plus500/' WHERE id = '023b98f5-9395-4ffa-b2ff-349392bdc41c'; -- Plus500
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/turnkey-security/', linkedin_company_url = 'https://www.linkedin.com/company/turnkey-security/' WHERE id = '02febeea-3202-46c0-a3f3-69e6ca389f6b'; -- turnkey
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/tapioca-dao/', linkedin_company_url = 'https://www.linkedin.com/company/tapioca-dao/' WHERE id = '06cc250b-1a67-4871-b199-734b2d077d46'; -- Tapioca
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/hermetica-fi/', linkedin_company_url = 'https://www.linkedin.com/company/hermetica-fi/' WHERE id = '075b7d96-c272-467d-a7d9-2a728f1e8904'; -- Hermetica
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/qiro-finance/', linkedin_company_url = 'https://www.linkedin.com/company/qiro-finance/' WHERE id = '07dd48d0-30e4-48e5-843e-882b4f08aa79'; -- Qiro
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/pyth-network/', linkedin_company_url = 'https://www.linkedin.com/company/pyth-network/' WHERE id = '09e1f1df-2426-4430-a32d-76a260f58c70'; -- Pyth
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/primer-api/', linkedin_company_url = 'https://www.linkedin.com/company/primer-api/' WHERE id = '09e6c59d-8011-4538-9101-5515f3a5eb0f'; -- Primer
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/metatimecoin/', linkedin_company_url = 'https://www.linkedin.com/company/metatimecoin/' WHERE id = '0ae6ff25-6eb1-4dd6-97a5-9115d6e899ec'; -- Metatime
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/belo-app/', linkedin_company_url = 'https://www.linkedin.com/company/belo-app/' WHERE id = '0b3c0573-742b-4e38-825a-ca4a2398c1d4'; -- belo
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/tap-payments/', linkedin_company_url = 'https://www.linkedin.com/company/tap-payments/' WHERE id = '0b88aff0-84a1-48fe-8c5e-0b0114a7511b'; -- Tap
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/superform-xyz/', linkedin_company_url = 'https://www.linkedin.com/company/superform-xyz/' WHERE id = '0c3f184a-b514-4a14-8393-252899379535'; -- Superform
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/salla-e-commerce/', linkedin_company_url = 'https://www.linkedin.com/company/salla-e-commerce/' WHERE id = '0e3b3cb0-957f-44fc-8139-0ff92e0133cc'; -- salla
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/perena/', linkedin_company_url = 'https://www.linkedin.com/company/perena/', website_url = 'https://perena.org' WHERE id = '0f255222-fe45-4912-a09a-5efd2ca28f23'; -- PERENA
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/toku-hq/', linkedin_company_url = 'https://www.linkedin.com/company/toku-hq/' WHERE id = '102b385a-442a-443a-a3bb-e1f69376bcd8'; -- TOKU
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/bitgo-inc/', linkedin_company_url = 'https://www.linkedin.com/company/bitgo-inc/' WHERE id = '1040b68a-c5ae-4da8-9119-9bfd144cfe79'; -- BitGo
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/holo-me/', linkedin_company_url = 'https://www.linkedin.com/company/holo-me/' WHERE id = '16fa2f14-930b-4f07-8bad-42a080c8c6b1'; -- Holo
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/fasset/', linkedin_company_url = 'https://www.linkedin.com/company/fasset/' WHERE id = '198d5bfb-5951-4d1b-94f6-5a34de44cdf3'; -- Fasset
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/ethena-labs/', linkedin_company_url = 'https://www.linkedin.com/company/ethena-labs/' WHERE id = '1ec2c656-bd2c-43f2-be09-0a89c29d6e7d'; -- Ethena
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/enjazbank/', linkedin_company_url = 'https://www.linkedin.com/company/enjazbank/' WHERE id = '1f1d0c20-f34c-45b7-b5f0-899a23c5df93'; -- enjaz
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/littio/', linkedin_company_url = 'https://www.linkedin.com/company/littio/' WHERE id = '205796a2-9cd8-417a-a915-541ed69d3a67'; -- littio
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/urpay/', linkedin_company_url = 'https://www.linkedin.com/company/urpay/' WHERE id = '20956209-ea3d-4991-8c55-cb772e775a71'; -- urpay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/codex-blockchain/', linkedin_company_url = 'https://www.linkedin.com/company/codex-blockchain/' WHERE id = '2280dfb3-1962-4582-a67b-c8be9896b30f'; -- CODEX
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/sary/', linkedin_company_url = 'https://www.linkedin.com/company/sary/' WHERE id = '24b6e8dc-906b-43db-a1a4-a2b6d6cf77db'; -- Sary
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/fireblocks/', linkedin_company_url = 'https://www.linkedin.com/company/fireblocks/' WHERE id = '275d45e0-8288-4697-bd4c-d6aa3a829296'; -- Fireblocks
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/level-usd/', linkedin_company_url = 'https://www.linkedin.com/company/level-usd/' WHERE id = '2949c3dc-bb4e-43f6-811e-ccd902a2e236'; -- Level
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/bijal/', linkedin_company_url = 'https://www.linkedin.com/company/bijal/', website_url = 'https://bijal.sa' WHERE id = '29b591b5-888d-4f7f-b485-f95fecb43b39'; -- Bijal
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/aave/', linkedin_company_url = 'https://www.linkedin.com/company/aave/' WHERE id = '2a5d600e-a5b3-4308-bb42-605ceb4bb49e'; -- Aave
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/satoshi-finance/', linkedin_company_url = 'https://www.linkedin.com/company/satoshi-finance/', website_url = 'https://satoshi.finance' WHERE id = '2a772b07-d9ec-4917-b74b-c9c5af479355'; -- Satoshi
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/brale/', linkedin_company_url = 'https://www.linkedin.com/company/brale/' WHERE id = '2b22b922-41f9-42c1-aac5-861194c0d456'; -- Brale
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/pleo/', linkedin_company_url = 'https://www.linkedin.com/company/pleo/' WHERE id = '2b718047-b417-4516-9275-4b3fd8cc3c1b'; -- Pleo
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/lambda-finance/', linkedin_company_url = 'https://www.linkedin.com/company/lambda-finance/', website_url = 'https://lambda.finance' WHERE id = '2b99b0aa-2e30-41f7-aac2-0bc5e88cb2d9'; -- LAMBDA
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/superstate-inc/', linkedin_company_url = 'https://www.linkedin.com/company/superstate-inc/' WHERE id = '2cf321a4-81b5-4bbd-9288-d99b18cfe093'; -- Superstate
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/western-union/', linkedin_company_url = 'https://www.linkedin.com/company/western-union/' WHERE id = '30538dfd-8649-4762-a848-ebda8895b926'; -- Western Union
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/smilee-finance/', linkedin_company_url = 'https://www.linkedin.com/company/smilee-finance/', website_url = 'https://smilee.finance' WHERE id = '3096268a-734d-4944-8807-3de479b58cce'; -- Smilee
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/spherepay/', linkedin_company_url = 'https://www.linkedin.com/company/spherepay/' WHERE id = '30d8c8df-7f67-4f73-b18b-d0326a9fc77f'; -- sphere
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/opendelta/', linkedin_company_url = 'https://www.linkedin.com/company/opendelta/', website_url = 'https://opendelta.finance' WHERE id = '30f5e67e-5c3a-4cbd-8f85-8770bdc70a4a'; -- Open Delta
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/kredete/', linkedin_company_url = 'https://www.linkedin.com/company/kredete/' WHERE id = '313060c4-674f-4287-b187-be41782a1f7a'; -- kredete
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/allium-labs/', linkedin_company_url = 'https://www.linkedin.com/company/allium-labs/' WHERE id = '31b0a4a4-0022-409c-a54f-e8115c68f970'; -- Allium
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/infinite-finance/', linkedin_company_url = 'https://www.linkedin.com/company/infinite-finance/', website_url = 'https://infinite.fi' WHERE id = '361eee83-cf51-4fd0-848d-c0e6d2eae361'; -- Infinite
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/openeden/', linkedin_company_url = 'https://www.linkedin.com/company/openeden/' WHERE id = '391c927f-2cc2-4e5b-9b03-bb69282422de'; -- OpenEden
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/coinsub/', linkedin_company_url = 'https://www.linkedin.com/company/coinsub/' WHERE id = '3952f542-8724-402a-8614-4f2eac4557b9'; -- coinsub
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/aptos-labs/', linkedin_company_url = 'https://www.linkedin.com/company/aptos-labs/' WHERE id = '3cf60134-3b40-4d87-9337-a8d7514ca3de'; -- Aptos Labs
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/okxofficial/', linkedin_company_url = 'https://www.linkedin.com/company/okxofficial/' WHERE id = '3d0a137f-bd54-4ba6-b67d-f49f11505acc'; -- OKX
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/stabir/', linkedin_company_url = 'https://www.linkedin.com/company/stabir/', website_url = 'https://stabir.io' WHERE id = '3e6bbc09-d352-4ccf-810d-6212dc4910c8'; -- StabIR
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/kast-app/', linkedin_company_url = 'https://www.linkedin.com/company/kast-app/' WHERE id = '3ed16e9f-b0f2-4db7-9d55-4e2b9c14e7ee'; -- KAST
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/stable-sea/', linkedin_company_url = 'https://www.linkedin.com/company/stable-sea/' WHERE id = '40c8c3d8-96b4-4201-91b4-863d76032f3c'; -- Stable Sea
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/cryptio/', linkedin_company_url = 'https://www.linkedin.com/company/cryptio/' WHERE id = '40fe0e53-663e-40e0-9eca-1da65ccfef03'; -- cryptio
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/chainlink-labs/', linkedin_company_url = 'https://www.linkedin.com/company/chainlink-labs/' WHERE id = '4130320f-3b53-47a5-ac55-9391cc8e51d7'; -- Chainlink
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/schuman-financial/', linkedin_company_url = 'https://www.linkedin.com/company/schuman-financial/' WHERE id = '41daa06a-1cec-4fac-9e7d-5769332215af'; -- Schuman Financial
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/bitpay/', linkedin_company_url = 'https://www.linkedin.com/company/bitpay/' WHERE id = '42537b27-6c03-4205-9cd8-7e0fedff50e0'; -- BitPay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/coinmama/', linkedin_company_url = 'https://www.linkedin.com/company/coinmama/' WHERE id = '42c962d6-896e-4211-a859-288065a1d9eb'; -- Coinmama
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/ledgerhq/', linkedin_company_url = 'https://www.linkedin.com/company/ledgerhq/' WHERE id = '444bf22c-312a-43b0-a400-acd53f6a5221'; -- Ledger
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/agora-finance/', linkedin_company_url = 'https://www.linkedin.com/company/agora-finance/' WHERE id = '44c9ffd7-e0fd-4849-9d63-4a134f9f71ff'; -- AGORA
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/tether-to/', linkedin_company_url = 'https://www.linkedin.com/company/tether-to/' WHERE id = '476b580c-09b8-4723-b9a3-d6f0900d597a'; -- Tether
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/circle-internet-financial/', linkedin_company_url = 'https://www.linkedin.com/company/circle-internet-financial/' WHERE id = '489197f8-a2a2-47ea-aabb-c03c503df3de'; -- Circle
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/fipto/', linkedin_company_url = 'https://www.linkedin.com/company/fipto/' WHERE id = '49fc4da4-d72d-4b83-bce1-37a0e9a0a4e9'; -- fipto
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/cap-finance/', linkedin_company_url = 'https://www.linkedin.com/company/cap-finance/', website_url = 'https://cap.finance' WHERE id = '4ada61dd-5379-4402-84bd-a62d20f05821'; -- CAP
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/neverless/', linkedin_company_url = 'https://www.linkedin.com/company/neverless/' WHERE id = '50a985f4-3f54-42c4-9a8b-34f764710ec6'; -- Neverless
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/klickl/', linkedin_company_url = 'https://www.linkedin.com/company/klickl/' WHERE id = '50f24a52-3bea-4031-a34c-bf4f361c950a'; -- Klickl
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/al-futtaim-group/', linkedin_company_url = 'https://www.linkedin.com/company/al-futtaim-group/' WHERE id = '524d251f-7c5d-4060-8c38-4826e3c6ebc0'; -- Al Futtaim Finance
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/alloyx/', linkedin_company_url = 'https://www.linkedin.com/company/alloyx/' WHERE id = '5277580c-293e-4e2b-aec7-1159a19d9fa7'; -- AlloyX
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/avalancheavax/', linkedin_company_url = 'https://www.linkedin.com/company/avalancheavax/' WHERE id = '531f4abc-4a7c-4343-81c2-9344ff6c50cf'; -- Avalanche
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/moonpay/', linkedin_company_url = 'https://www.linkedin.com/company/moonpay/' WHERE id = '534334ec-ce7b-4938-a972-9a25136f24d8'; -- Moonpay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/arf-financial/', linkedin_company_url = 'https://www.linkedin.com/company/arf-financial/' WHERE id = '5635c266-f411-45f0-a4dd-0f63b9cabf4e'; -- Arf
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/mansa-finance/', linkedin_company_url = 'https://www.linkedin.com/company/mansa-finance/', website_url = 'https://mansa.finance' WHERE id = '56e7270b-1698-4422-ac23-0d7cfb684193'; -- MANSA
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/resolv-labs/', linkedin_company_url = 'https://www.linkedin.com/company/resolv-labs/' WHERE id = '59298044-7ef1-48c3-af4b-c781255381d0'; -- RESOLV
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/verity-tech/', linkedin_company_url = 'https://www.linkedin.com/company/verity-tech/', website_url = 'https://verity.ae' WHERE id = '5b527452-f278-4267-9157-1a3e1cd23d04'; -- Verity
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/vertofx/', linkedin_company_url = 'https://www.linkedin.com/company/vertofx/', website_url = 'https://verto.co' WHERE id = '5c679f1c-a070-41a7-aad3-b90ae8e40bf3'; -- Verto
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/meshconnect/', linkedin_company_url = 'https://www.linkedin.com/company/meshconnect/' WHERE id = '5fcbd96f-f43a-4f46-9ab8-8c65ad04de51'; -- MESH
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/manta-network/', linkedin_company_url = 'https://www.linkedin.com/company/manta-network/' WHERE id = '6084e769-c32f-445c-80a3-332f773363f4'; -- MANTA
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/ekar/', linkedin_company_url = 'https://www.linkedin.com/company/ekar/' WHERE id = '61a4af06-324e-43ea-afd8-cef4fe519419'; -- Ekar
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/pexxapp/', linkedin_company_url = 'https://www.linkedin.com/company/pexxapp/' WHERE id = '620a9a03-b1a3-4798-a1bd-0279b97ea17a'; -- PEXX
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/single-view/', linkedin_company_url = 'https://www.linkedin.com/company/single-view/' WHERE id = '646224d3-2523-4c1b-aa7d-c7f7239ba907'; -- Single View
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/fortunafi/', linkedin_company_url = 'https://www.linkedin.com/company/fortunafi/', website_url = 'https://fortunafi.com' WHERE id = '666e7e14-4cf5-4735-8143-b9aacc64ee37'; -- fortunafi
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/tazapay/', linkedin_company_url = 'https://www.linkedin.com/company/tazapay/' WHERE id = '668cab19-bb07-4f29-91cb-bf12fadc3252'; -- Tazapay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/parallax-finance/', linkedin_company_url = 'https://www.linkedin.com/company/parallax-finance/' WHERE id = '66944577-f5b3-4c8e-ada6-fbacae183d1d'; -- parallax
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/hyperpay/', linkedin_company_url = 'https://www.linkedin.com/company/hyperpay/' WHERE id = '691ff4f8-0db7-42c5-9db2-38c5e5dd2d12'; -- Hyperpay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/elfi-protocol/', linkedin_company_url = 'https://www.linkedin.com/company/elfi-protocol/', website_url = 'https://elfi.finance' WHERE id = '6a118fc6-2fc0-4a07-bc88-4a45eef0a576'; -- ELFi
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/zerohash/', linkedin_company_url = 'https://www.linkedin.com/company/zerohash/' WHERE id = '6a97a878-99c4-447d-8453-5443c4ea0fd0'; -- ZeroHash
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/limitedfinance/', linkedin_company_url = 'https://www.linkedin.com/company/limitedfinance/', website_url = 'https://limited.finance' WHERE id = '6b12f8c0-db4b-46dd-8788-484868695e4e'; -- LIMITED
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/nuvei/', linkedin_company_url = 'https://www.linkedin.com/company/nuvei/' WHERE id = '6bac20de-b592-4889-8f52-968ca17c2ba7'; -- Nuvei
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/haraka-africa/', linkedin_company_url = 'https://www.linkedin.com/company/haraka-africa/', website_url = 'https://haraka.africa' WHERE id = '6bad8dd7-2a86-448d-9985-562818984b65'; -- HARAKA
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/bankable/', linkedin_company_url = 'https://www.linkedin.com/company/bankable/' WHERE id = '6c46df90-7668-4503-a007-938455a00571'; -- Bankable
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/portaldefi/', linkedin_company_url = 'https://www.linkedin.com/company/portaldefi/' WHERE id = '6ea214ff-1eb1-422b-bedb-d24185e9c8ba'; -- Portal
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/sarie/', linkedin_company_url = 'https://www.linkedin.com/company/sarie/' WHERE id = '6fba6e00-c8f2-4f32-8907-7a7e77f56fce'; -- sarie
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/zepzpay/', linkedin_company_url = 'https://www.linkedin.com/company/zepzpay/' WHERE id = '70f1d64f-98b2-473f-bc00-aa7501b74639'; -- Zepz
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/stakestone/', linkedin_company_url = 'https://www.linkedin.com/company/stakestone/', website_url = 'https://stakestone.io' WHERE id = '72582b16-8df7-4736-a211-10f456fa35b9'; -- StakeStone
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/elixir-protocol/', linkedin_company_url = 'https://www.linkedin.com/company/elixir-protocol/' WHERE id = '75053e3d-f3b7-44d9-99c0-1338bef37cca'; -- Elixir
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/stables-app/', linkedin_company_url = 'https://www.linkedin.com/company/stables-app/' WHERE id = '768899bf-fc34-43c4-801b-576a4118b586'; -- stables
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/plasma-finance/', linkedin_company_url = 'https://www.linkedin.com/company/plasma-finance/' WHERE id = '76f9bfab-f922-42f7-bc48-2e475b93b6bb'; -- Plasma
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/network-international/', linkedin_company_url = 'https://www.linkedin.com/company/network-international/' WHERE id = '77c9fc15-1efc-4f9c-97dc-08c0b26f0134'; -- Network International
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/riseworks/', linkedin_company_url = 'https://www.linkedin.com/company/riseworks/' WHERE id = '7922e25b-9dce-4b6c-8f8e-3c1b305df7c1'; -- rise
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/elm/', linkedin_company_url = 'https://www.linkedin.com/company/elm/' WHERE id = '7a04f536-f93a-4fad-b1c4-eadc4c6aa370'; -- Elm
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/transak/', linkedin_company_url = 'https://www.linkedin.com/company/transak/' WHERE id = '7c25768c-ad1b-41e3-b639-446accd4c8d3'; -- Transak
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/usdx-money/', linkedin_company_url = 'https://www.linkedin.com/company/usdx-money/' WHERE id = '7d2ca78c-3a2b-467d-8cfc-9a8aad1e1e1e'; -- USDX
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/wspn/', linkedin_company_url = 'https://www.linkedin.com/company/wspn/' WHERE id = '7f887e2c-47ec-40b2-904f-9dbaab2d0c7e'; -- WSPN
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/neotek-fintech/', linkedin_company_url = 'https://www.linkedin.com/company/neotek-fintech/' WHERE id = '7f8cfa31-92af-40fc-8f15-6e0eed9254f3'; -- NeoTek
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/usual-money/', linkedin_company_url = 'https://www.linkedin.com/company/usual-money/' WHERE id = '80094a11-bd3a-4f31-b526-1431e23bc358'; -- USUAL
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/nowmoney/', linkedin_company_url = 'https://www.linkedin.com/company/nowmoney/' WHERE id = '803138c1-c2c5-4f14-b064-20076ada0e44'; -- Now Money
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/madfu/', linkedin_company_url = 'https://www.linkedin.com/company/madfu/' WHERE id = '8078fa53-e6a5-4b9a-b3fe-69693a7a56ef'; -- madfu
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/avalonlabs/', linkedin_company_url = 'https://www.linkedin.com/company/avalonlabs/' WHERE id = '80f0f847-2c69-4b99-9bd8-2fd147d2cf52'; -- Avalon Labs
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/noah-money/', linkedin_company_url = 'https://www.linkedin.com/company/noah-money/' WHERE id = '8112afc0-1abc-4b81-9b69-fd55dfccfd1a'; -- NOAH
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/foodics/', linkedin_company_url = 'https://www.linkedin.com/company/foodics/' WHERE id = '819f6c96-1e3a-497f-bf24-12e1aded4c4e'; -- Foodics Pay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/ampleforth/', linkedin_company_url = 'https://www.linkedin.com/company/ampleforth/' WHERE id = '81bed55c-056f-4470-aabc-1c6b5bb4bbd2'; -- Ampleforth
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/talentir/', linkedin_company_url = 'https://www.linkedin.com/company/talentir/' WHERE id = '8243625e-bc0d-4d29-8caa-c25bab301ae3'; -- talentir
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/tamam-app/', linkedin_company_url = 'https://www.linkedin.com/company/tamam-app/' WHERE id = '826ceec1-ba06-41cb-9d4f-d0b7ade0f451'; -- Tamam
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/eldorado-market/', linkedin_company_url = 'https://www.linkedin.com/company/eldorado-market/' WHERE id = '8303a62e-e2d2-4865-8e49-ca789bedc8ec'; -- El Dorado
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/morpho-labs/', linkedin_company_url = 'https://www.linkedin.com/company/morpho-labs/' WHERE id = '8696027a-ee60-43c1-b083-cd4a48a6e4f7'; -- Morpho
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/rd-technologies/', linkedin_company_url = 'https://www.linkedin.com/company/rd-technologies/' WHERE id = '8743bf00-28d2-463d-b72f-0ded0895720a'; -- RD Technologies
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/harpfi/', linkedin_company_url = 'https://www.linkedin.com/company/harpfi/' WHERE id = '8767fa12-bb40-4352-a308-e572644b947d'; -- HarpFi
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/mountain-protocol/', linkedin_company_url = 'https://www.linkedin.com/company/mountain-protocol/' WHERE id = '88bd5a4e-ffc9-4cca-93a5-5eb6453f4993'; -- Mountain Protocol
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/rafiki-foundation/', linkedin_company_url = 'https://www.linkedin.com/company/rafiki-foundation/' WHERE id = '88f69d22-28ce-41d8-a283-8e9a53bbe7c0'; -- Rafiki
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/brla-digital/', linkedin_company_url = 'https://www.linkedin.com/company/brla-digital/' WHERE id = '8b2248e5-ae90-41ed-b52b-63a1a0c18826'; -- BRLA
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/unipass-wallet/', linkedin_company_url = 'https://www.linkedin.com/company/unipass-wallet/' WHERE id = '8b7a8d09-98fb-4c64-8301-043fd9ec3cfa'; -- UniPass
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/multibankgroup/', linkedin_company_url = 'https://www.linkedin.com/company/multibankgroup/' WHERE id = '8d8fa5ac-479c-4523-a28c-50f65b86bd4e'; -- Multibank
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/crossmint/', linkedin_company_url = 'https://www.linkedin.com/company/crossmint/' WHERE id = '8daffb22-6ff4-489c-ab39-2f5dc96655f1'; -- crossmint
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/payfabs/', linkedin_company_url = 'https://www.linkedin.com/company/payfabs/', website_url = 'https://payfabs.io' WHERE id = '8ee945b3-fff4-493b-be75-92367405d629'; -- Payfabs
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/torch-finance/', linkedin_company_url = 'https://www.linkedin.com/company/torch-finance/', website_url = 'https://torchfinance.xyz' WHERE id = '8f52b3ef-3fa3-483c-8c2a-c6468c391e79'; -- TORCH
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/mangopay/', linkedin_company_url = 'https://www.linkedin.com/company/mangopay/' WHERE id = '92f730fb-756f-420a-9871-505f6356e2dc'; -- MangoPay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/aegis-labs/', linkedin_company_url = 'https://www.linkedin.com/company/aegis-labs/' WHERE id = '933e292d-ed4a-455e-90f9-d5dbf4344d93'; -- Aegis
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/sling-money/', linkedin_company_url = 'https://www.linkedin.com/company/sling-money/' WHERE id = '937226b3-5df4-45bb-bbb2-7efa4a8b53cc'; -- Slingmoney
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/next-generation-finance/', linkedin_company_url = 'https://www.linkedin.com/company/next-generation-finance/', website_url = 'https://nextgen.finance' WHERE id = '93fc25db-79e0-48a7-be7f-3b8ad892ab2d'; -- Next Generation
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/payrails/', linkedin_company_url = 'https://www.linkedin.com/company/payrails/' WHERE id = '94c7f3d1-e93d-4e5a-bbd0-f63e2ec0a97f'; -- Payrails
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/buildnow/', linkedin_company_url = 'https://www.linkedin.com/company/buildnow/' WHERE id = '952b0585-4cbe-4d51-9883-d60f9fb6d630'; -- Buildnow
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/friendipay/', linkedin_company_url = 'https://www.linkedin.com/company/friendipay/', website_url = 'https://friendipay.com' WHERE id = '9806bb96-26eb-4852-9b10-8af19b622be5'; -- friendi pay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/bluechip-finance/', linkedin_company_url = 'https://www.linkedin.com/company/bluechip-finance/' WHERE id = '999d73b9-2116-4742-9979-bd716768e63c'; -- Bluechip
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/open-settlements/', linkedin_company_url = 'https://www.linkedin.com/company/open-settlements/', website_url = 'https://opensettlements.com' WHERE id = '9a6c5108-3de0-4add-9296-dedccc89026c'; -- Open Settlements
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/ouilting/', linkedin_company_url = 'https://www.linkedin.com/company/ouilting/', website_url = 'https://ouilting.io' WHERE id = '9a7e30ab-7c91-4f41-897b-6f5a0ba96f1b'; -- OuilTing
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/karsa/', linkedin_company_url = 'https://www.linkedin.com/company/karsa/' WHERE id = '9ad5d171-5d2d-402b-bda9-8bb3ca7fe15d'; -- karsa
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/eywa-defi/', linkedin_company_url = 'https://www.linkedin.com/company/eywa-defi/', website_url = 'https://eywa.fi' WHERE id = '9b75aea8-fe70-4087-ab1b-2e7e53d0af56'; -- eywa
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/openpayd/', linkedin_company_url = 'https://www.linkedin.com/company/openpayd/' WHERE id = '9d8e5d56-cfdc-48cf-b073-920b18a9872f'; -- OpenPayd
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/utila-io/', linkedin_company_url = 'https://www.linkedin.com/company/utila-io/' WHERE id = '9e7d2cc3-63a6-40d4-8edd-4b2d393daaf3'; -- utila
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/stable-jack/', linkedin_company_url = 'https://www.linkedin.com/company/stable-jack/', website_url = 'https://stablejack.finance' WHERE id = '9e8115e5-e674-4dc0-b49b-502707d6c061'; -- Stable Jack
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/quantoz/', linkedin_company_url = 'https://www.linkedin.com/company/quantoz/' WHERE id = '9ee52a1a-01fb-4055-8580-7c1a5e37390a'; -- QuantOZ
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/nexusmutual/', linkedin_company_url = 'https://www.linkedin.com/company/nexusmutual/', website_url = 'https://nexusmutual.io' WHERE id = 'a015c901-cb54-4c42-ac95-7cf213e36535'; -- nexus
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/alinmapay/', linkedin_company_url = 'https://www.linkedin.com/company/alinmapay/' WHERE id = 'a11eb6ec-7085-4903-828c-09376e521c10'; -- alinma
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/coinmetrics/', linkedin_company_url = 'https://www.linkedin.com/company/coinmetrics/' WHERE id = 'a160fb86-cff3-4fed-88b5-a69f2851c1d1'; -- CoinMetrics
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/mento-labs/', linkedin_company_url = 'https://www.linkedin.com/company/mento-labs/' WHERE id = 'a2b766bd-a791-4f8f-b861-972c03f96982'; -- Mento Labs
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/noble-fi/', linkedin_company_url = 'https://www.linkedin.com/company/noble-fi/' WHERE id = 'a2f4b696-ea70-4218-a9a8-c0a474073354'; -- Noble
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/koywe/', linkedin_company_url = 'https://www.linkedin.com/company/koywe/' WHERE id = 'a34e8f5b-2632-49cd-a20c-a7532b8f87ec'; -- koywe
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/amlak-international/', linkedin_company_url = 'https://www.linkedin.com/company/amlak-international/' WHERE id = 'a3af0541-60d2-4041-8d34-587939b281ad'; -- Amlak International
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/sling-money/', linkedin_company_url = 'https://www.linkedin.com/company/sling-money/' WHERE id = 'a47a08b0-19fe-489f-89db-2eef98107def'; -- Sling Money
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/etherfuse/', linkedin_company_url = 'https://www.linkedin.com/company/etherfuse/' WHERE id = 'a514882c-a54a-407e-b534-e80b7ea5c8f7'; -- etherfuse
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/ppro/', linkedin_company_url = 'https://www.linkedin.com/company/ppro/' WHERE id = 'a55a7fc4-41a5-4f3a-b2ec-64c6da7c85e6'; -- PPRO
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/caliza/', linkedin_company_url = 'https://www.linkedin.com/company/caliza/' WHERE id = 'a6c2053e-1f6a-4cb4-bf7a-b09e86a1ecb6'; -- caliza
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/openzk/', linkedin_company_url = 'https://www.linkedin.com/company/openzk/', website_url = 'https://openzk.network' WHERE id = 'a7b4dd15-8b90-40f5-9887-f84382634441'; -- OpenZK
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/alinmapay/', linkedin_company_url = 'https://www.linkedin.com/company/alinmapay/' WHERE id = 'a81a1ce5-4b60-48cb-adff-4b9067c82018'; -- Alinma Pay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/tahweel-al-rajhi/', linkedin_company_url = 'https://www.linkedin.com/company/tahweel-al-rajhi/' WHERE id = 'a87fb8a9-49f7-463a-814f-c6d19e3a3ad8'; -- Tahweel Al Rajhi
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/shield-finance/', linkedin_company_url = 'https://www.linkedin.com/company/shield-finance/', website_url = 'https://shield.finance' WHERE id = 'a8b13186-1abd-4adf-96d6-878bc445b538'; -- Shield
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/paytaca/', linkedin_company_url = 'https://www.linkedin.com/company/paytaca/' WHERE id = 'a9d03cab-4454-4ef2-ac7c-ad1747b977ca'; -- Paytaca
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/elliptic/', linkedin_company_url = 'https://www.linkedin.com/company/elliptic/' WHERE id = 'a9f68a72-c132-4b29-82ae-00e69fd5c862'; -- Elliptic
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/dfns/', linkedin_company_url = 'https://www.linkedin.com/company/dfns/' WHERE id = 'aac8206e-bdde-40a4-bec4-ea5510a64eb4'; -- Dfns
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/salt-lending/', linkedin_company_url = 'https://www.linkedin.com/company/salt-lending/', website_url = 'https://salt.lending' WHERE id = 'ab9ee2fe-5846-4bbd-bea0-e80339e71f69'; -- SALT
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/router-protocol/', linkedin_company_url = 'https://www.linkedin.com/company/router-protocol/' WHERE id = 'ad22e239-0671-42db-ab1c-fcae0f9506d1'; -- Router Protocol
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/centi-ch/', linkedin_company_url = 'https://www.linkedin.com/company/centi-ch/' WHERE id = 'ad3adbe6-5137-4c8e-8972-fa2325029aee'; -- CENTI
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/ton-blockchain/', linkedin_company_url = 'https://www.linkedin.com/company/ton-blockchain/' WHERE id = 'afde415f-7d49-4548-b4f4-babc46688f3c'; -- TON
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/quicknode/', linkedin_company_url = 'https://www.linkedin.com/company/quicknode/' WHERE id = 'b4085243-2ed3-490b-83ab-3c210aafa37f'; -- QuickNode
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/jpyc-inc/', linkedin_company_url = 'https://www.linkedin.com/company/jpyc-inc/' WHERE id = 'b45514fc-d69b-4162-860b-680689781564'; -- JPYC
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/banked-limited/', linkedin_company_url = 'https://www.linkedin.com/company/banked-limited/', website_url = 'https://banked.com' WHERE id = 'b5c910bd-e35a-4ab2-80a2-72ea13fdf068'; -- Banked
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/thalex/', linkedin_company_url = 'https://www.linkedin.com/company/thalex/' WHERE id = 'b5d334d1-6e4c-4ce6-bf63-84c368ff70c2'; -- Thalex
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/mnt-halan/', linkedin_company_url = 'https://www.linkedin.com/company/mnt-halan/' WHERE id = 'b6a7947a-2897-4fcf-9f35-157c5b41d60e'; -- MNT Halan
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/solv-protocol/', linkedin_company_url = 'https://www.linkedin.com/company/solv-protocol/' WHERE id = 'b6d39840-8777-42df-9672-b0e8026df900'; -- Solv
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/redstone-oracles/', linkedin_company_url = 'https://www.linkedin.com/company/redstone-oracles/' WHERE id = 'b740bd76-f501-474d-8e31-2ec3570a74c4'; -- RedStone
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/jadecity/', linkedin_company_url = 'https://www.linkedin.com/company/jadecity/', website_url = 'https://jadecity.io' WHERE id = 'b820103e-8386-4b52-b1f0-e432a24844c5'; -- JadeCity
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/proven-finance/', linkedin_company_url = 'https://www.linkedin.com/company/proven-finance/', website_url = 'https://proven.xyz' WHERE id = 'ba4deaa9-5d3f-43f4-9b26-567d58bf28e2'; -- Proven
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/ivorypay/', linkedin_company_url = 'https://www.linkedin.com/company/ivorypay/' WHERE id = 'bae71288-9897-439c-b813-828908b25574'; -- ivorypay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/huma-finance/', linkedin_company_url = 'https://www.linkedin.com/company/huma-finance/' WHERE id = 'bd794e8d-6338-450f-95b8-75e15592890a'; -- Huma
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/nilos-crypto/', linkedin_company_url = 'https://www.linkedin.com/company/nilos-crypto/' WHERE id = 'c0457ecd-2c05-474a-9053-a2c9a0595120'; -- nilos
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/chainalysis/', linkedin_company_url = 'https://www.linkedin.com/company/chainalysis/' WHERE id = 'c22dab2d-f5c0-4b7b-90f0-c422ea5a192a'; -- Chainalysis
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/acctual/', linkedin_company_url = 'https://www.linkedin.com/company/acctual/' WHERE id = 'c260fc3a-8117-4320-80e3-7a2023678a81'; -- Acctual
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/due-finance/', linkedin_company_url = 'https://www.linkedin.com/company/due-finance/', website_url = 'https://due.com' WHERE id = 'c62d8399-3f09-453f-ba15-8e2ee8029e64'; -- due
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/bima-mobile/', linkedin_company_url = 'https://www.linkedin.com/company/bima-mobile/' WHERE id = 'c7d420ac-3092-4580-9432-70e013aa0a5b'; -- BIMA
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/galactic-holdings/', linkedin_company_url = 'https://www.linkedin.com/company/galactic-holdings/', website_url = 'https://galactic.holdings' WHERE id = 'c83566c3-26e5-44e2-a71f-59ff3b5b9fe7'; -- Galactic Holdings
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/cypher-wallet/', linkedin_company_url = 'https://www.linkedin.com/company/cypher-wallet/' WHERE id = 'c8aadf16-3766-48a0-8158-c818fbb09deb'; -- Cypher
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/phantom-wallet/', linkedin_company_url = 'https://www.linkedin.com/company/phantom-wallet/' WHERE id = 'c8f09fbd-7cf9-46c4-bab8-a0902d3e72a8'; -- Phantom
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/alchemy-pay/', linkedin_company_url = 'https://www.linkedin.com/company/alchemy-pay/' WHERE id = 'cc374817-a915-485a-b64f-b54090af17da'; -- Alchemy Pay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/akaunt/', linkedin_company_url = 'https://www.linkedin.com/company/akaunt/', website_url = 'https://akaunt.io' WHERE id = 'cd3d8d26-08eb-4073-ab1c-b08e540826cd'; -- akaunt
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/credable/', linkedin_company_url = 'https://www.linkedin.com/company/credable/' WHERE id = 'ce1daade-eb28-4360-9829-c03b3100b2b6'; -- Credable
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/visa/', linkedin_company_url = 'https://www.linkedin.com/company/visa/', website_url = 'https://www.visa.com' WHERE id = 'cfe390ff-7120-4d3e-b3b6-ff42e5788f9a'; -- Visa
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/triple-a-technologies/', linkedin_company_url = 'https://www.linkedin.com/company/triple-a-technologies/' WHERE id = 'd34b13c7-3f7b-4ce3-b0f5-3bd7760786bf'; -- Triple A
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/pay10/', linkedin_company_url = 'https://www.linkedin.com/company/pay10/' WHERE id = 'd3e62561-61f6-4cf5-8967-e773cf9e0e20'; -- Pay10
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/privy-io/', linkedin_company_url = 'https://www.linkedin.com/company/privy-io/' WHERE id = 'd470da5a-cf26-4b55-b5b4-4a5524c1dddd'; -- privy
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/bvnk/', linkedin_company_url = 'https://www.linkedin.com/company/bvnk/' WHERE id = 'd5313a5b-721a-4215-ac21-2b44e08be976'; -- BVNK
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/instadapp/', linkedin_company_url = 'https://www.linkedin.com/company/instadapp/' WHERE id = 'd6ddaf16-419e-486e-835d-2ab1a770c387'; -- Fluid Protocol
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/paysafe/', linkedin_company_url = 'https://www.linkedin.com/company/paysafe/' WHERE id = 'd7dc7487-8985-4175-a783-d78f08dfad02'; -- Paysafe
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/ramp-network/', linkedin_company_url = 'https://www.linkedin.com/company/ramp-network/' WHERE id = 'db1054db-38ec-4e4b-ac57-68598dc965a5'; -- Ramp
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/dynamic-xyz/', linkedin_company_url = 'https://www.linkedin.com/company/dynamic-xyz/' WHERE id = 'dba1f894-5430-48e7-8a5b-aa7cec59566c'; -- dynamic
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/yellowcardapp/', linkedin_company_url = 'https://www.linkedin.com/company/yellowcardapp/' WHERE id = 'dbbb1066-742f-4c3f-b445-ca75bea17e48'; -- Yellowcard
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/ida-finance/', linkedin_company_url = 'https://www.linkedin.com/company/ida-finance/', website_url = 'https://ida.finance' WHERE id = 'dbe68548-b096-4cc1-baf1-dc3316d28450'; -- IDA
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/flowdesk/', linkedin_company_url = 'https://www.linkedin.com/company/flowdesk/' WHERE id = 'ddee7802-9f31-4b59-82ca-79694ea1080a'; -- Flowdesk
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/sixclovers/', linkedin_company_url = 'https://www.linkedin.com/company/sixclovers/' WHERE id = 'de63e201-f14b-4412-85ea-1de7266d84f4'; -- Six Clovers
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/mastercard/', linkedin_company_url = 'https://www.linkedin.com/company/mastercard/', website_url = 'https://www.mastercard.com' WHERE id = 'de8d6133-cb0f-4128-bdda-4409a6f103e8'; -- Mastercard
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/sokin/', linkedin_company_url = 'https://www.linkedin.com/company/sokin/' WHERE id = 'ded3169d-7264-465b-b67b-15568583c970'; -- Sokin
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/securitize/', linkedin_company_url = 'https://www.linkedin.com/company/securitize/' WHERE id = 'dfaa58dd-7c10-4a88-9b1d-18ea2d7bcd7c'; -- Securitize
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/anzen-finance/', linkedin_company_url = 'https://www.linkedin.com/company/anzen-finance/' WHERE id = 'e09f1b7e-e201-4dec-bade-fbb504aead36'; -- anzen
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/borderless-xyz/', linkedin_company_url = 'https://www.linkedin.com/company/borderless-xyz/' WHERE id = 'e710bc10-eca0-4e71-b468-9013b7a1b298'; -- Borderless.xyz
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/m0-foundation/', linkedin_company_url = 'https://www.linkedin.com/company/m0-foundation/' WHERE id = 'e99dbf12-b0be-4001-bbe2-fc6cf3bde3c5'; -- M0
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/yellowcardapp/', linkedin_company_url = 'https://www.linkedin.com/company/yellowcardapp/', website_url = 'https://yellowcard.io' WHERE id = 'e9a95304-bc41-422d-b496-2a78049ecb9e'; -- Yellow Card
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/zoth-fi/', linkedin_company_url = 'https://www.linkedin.com/company/zoth-fi/' WHERE id = 'ea55dc49-4607-4139-b3e0-6a1ce4ab2185'; -- Zoth
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/baanx-group/', linkedin_company_url = 'https://www.linkedin.com/company/baanx-group/' WHERE id = 'eb51fb7d-4cdf-4670-97be-200e56dfce92'; -- BAANX
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/salt-edge/', linkedin_company_url = 'https://www.linkedin.com/company/salt-edge/' WHERE id = 'ecaa1cb5-0464-4780-8b72-8a832a4da6fc'; -- Salt Edge
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/mural-pay/', linkedin_company_url = 'https://www.linkedin.com/company/mural-pay/' WHERE id = 'ece9f977-9244-4659-b3c0-68089caaae5e'; -- MURAL
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/aquanow/', linkedin_company_url = 'https://www.linkedin.com/company/aquanow/' WHERE id = 'ed5b5888-210c-4692-b7a1-32ac0c27daf1'; -- Aquanow
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/sbc-fintech/', linkedin_company_url = 'https://www.linkedin.com/company/sbc-fintech/', website_url = 'https://sbc.finance' WHERE id = 'ee36d3ee-41a6-4a99-baa0-684c0e390772'; -- SBC
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/coinchange/', linkedin_company_url = 'https://www.linkedin.com/company/coinchange/' WHERE id = 'ef186fdb-0478-4dc9-af2e-ff0af4caca94'; -- coinchange
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/coinflow-io/', linkedin_company_url = 'https://www.linkedin.com/company/coinflow-io/' WHERE id = 'ef2b5d5a-7c4b-4bc1-b893-e7c42e5d01bc'; -- Coinflow
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/jahez/', linkedin_company_url = 'https://www.linkedin.com/company/jahez/' WHERE id = 'eff16a93-487e-4a66-b896-501db8551f05'; -- Jahez
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/kotani-pay/', linkedin_company_url = 'https://www.linkedin.com/company/kotani-pay/' WHERE id = 'f06d3292-84dd-4a94-8892-b8bf99abe96d'; -- Kotani Pay
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/opentrade-finance/', linkedin_company_url = 'https://www.linkedin.com/company/opentrade-finance/' WHERE id = 'f08bb1aa-84c4-49ea-8907-7f65996d511c'; -- OpenTrade
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/myatooorah/', linkedin_company_url = 'https://www.linkedin.com/company/myatooorah/' WHERE id = 'f1f64ce3-8f50-4785-a702-aa1b752e9b70'; -- myatooorah
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/sati-fintech/', linkedin_company_url = 'https://www.linkedin.com/company/sati-fintech/' WHERE id = 'f2d97f8f-b823-4d77-9ab6-3ede71c5e0ff'; -- sati
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/sparefintech/', linkedin_company_url = 'https://www.linkedin.com/company/sparefintech/' WHERE id = 'f3bfb650-ab19-47ac-b6c7-f101f5ceb15e'; -- Spare
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/dannisa/', linkedin_company_url = 'https://www.linkedin.com/company/dannisa/', website_url = 'https://dannisa.com' WHERE id = 'f3e59d94-ad35-4cec-949f-2c1df462fa37'; -- Dannisa
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/meso-network/', linkedin_company_url = 'https://www.linkedin.com/company/meso-network/' WHERE id = 'f69e3db5-ac87-4293-9885-887bacdb2d94'; -- Meso
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/truex-co/', linkedin_company_url = 'https://www.linkedin.com/company/truex-co/' WHERE id = 'f73b099c-9dd2-4c76-a53f-e6f35d3b36e5'; -- TrueX
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/blast-l2/', linkedin_company_url = 'https://www.linkedin.com/company/blast-l2/', website_url = 'https://blast.io' WHERE id = 'f8cbb32a-8744-4aee-80ee-d6cf6301129d'; -- BLAST
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/0xpolygon/', linkedin_company_url = 'https://www.linkedin.com/company/0xpolygon/' WHERE id = 'faac98ea-421b-46ae-9f11-23f267db3f93'; -- Polygon
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/bitwave-io/', linkedin_company_url = 'https://www.linkedin.com/company/bitwave-io/' WHERE id = 'fb0e7d63-ca39-47fe-a0b6-8c7898fd2105'; -- BITWAVE
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/layerzero-labs/', linkedin_company_url = 'https://www.linkedin.com/company/layerzero-labs/' WHERE id = 'fc0e594b-f4ce-4d8b-b02d-038afa5fb3d7'; -- LayerZero
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/cenoa/', linkedin_company_url = 'https://www.linkedin.com/company/cenoa/' WHERE id = 'fd89447f-4253-4ef5-993a-ea67412b6b9d'; -- cenoa
UPDATE companies SET linkedin_url = 'https://www.linkedin.com/company/uniswap-labs/', linkedin_company_url = 'https://www.linkedin.com/company/uniswap-labs/' WHERE id = 'fe9a632b-81d4-4113-8333-08d11a039a4a'; -- Uniswap

COMMIT;
